"""Generates the MuJoCo model from config.json.

    python tools/make_mjcf.py [config.json] [-o tools/pendulum.xml]

The model is GENERATED, never hand-edited. config.json is the single source of
truth for hardware numbers, and a hand-written XML carrying its own "mass=0.12"
would be a second one -- which is exactly the failure that cost the first training
run, in a new place. Edit config.json and re-run this.

Conventions, chosen to match core/ exactly so the two can be compared:

  theta = 0 is UPRIGHT, theta = pi is hanging, matching core::State.
    The chain is therefore built pointing +Z in the reference pose. Build it
    hanging instead and every angle is off by pi, which reads as a sign error in
    the dynamics rather than as a modelling mistake.

  Positive theta tips the link toward +x, matching the -a*cos(theta) carriage
    coupling in Plant::accel. A hinge about +Y takes a point at (0,0,L) to
    (L sin th, 0, L cos th), which is that sign.

  diaginertia is about the body's own centre of mass, which is what
    PendulumParams::inertias means. Letting MuJoCo infer inertia from a geom
    instead would silently use the geom's inertia and diverge from core.

  Contacts are disabled everywhere. The rail limit and step loss are decided in
    code, not by the constraint solver, and a comparison against core has to be
    pure rigid-body.
"""
import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def load_config(path):
    text = open(path, encoding="utf-8").read()
    # config.json permits // comments via nlohmann's ignore_comments; json does not.
    text = re.sub(r"^\s*//.*$", "", text, flags=re.M)
    return json.loads(text)


def link_bodies(links, depth=0, indent="      "):
    """Nested <body> elements, one per link, each pinned at the end of its parent.

    Every link gets its OWN body, including the first -- it does not share the
    cart's. MuJoCo allows one <inertial> per body, so folding link 1 into the cart
    both fails to load and would have meant the link's mass sat on the carriage.
    """
    if depth >= len(links):
        return ""
    link = links[depth]
    length = link["length"]
    inertia = link["inertia"]
    # Planar motion only rotates about Y, so Iyy is the number that matters. Ixx is
    # equal for a rod, and Izz is set small but non-zero: MuJoCo requires positive
    # inertia obeying the triangle inequality, and a rod's spin inertia is ~0.
    izz = max(inertia * 1e-3, 1e-12)
    # Link 1 pivots at the carriage; every later link pivots at the far end of the
    # one before it.
    offset = "0 0 0" if depth == 0 else f"0 0 {links[depth-1]['length']:.9g}"
    inner = indent + "  "
    child = link_bodies(links, depth + 1, inner)

    return f"""{indent}<body name="link{depth+1}" pos="{offset}">
{inner}<joint name="theta{depth+1}" type="hinge" axis="0 1 0" damping="{link['joint_damping']:.9g}"/>
{inner}<inertial pos="0 0 {link['com_dist']:.9g}" mass="{link['mass']:.9g}"
{inner}          diaginertia="{inertia:.9g} {inertia:.9g} {izz:.9g}"/>
{inner}<geom name="rod{depth+1}" type="capsule" fromto="0 0 0 0 0 {length:.9g}"
{inner}      size="0.008" rgba="0.16 0.47 0.84 1" contype="0" conaffinity="0"/>
{inner}<geom name="pivot{depth+1}" type="sphere" pos="0 0 0" size="0.014"
{inner}      rgba="0.92 0.41 0.20 1" contype="0" conaffinity="0"/>
{child}{indent}</body>
"""


def build(cfg):
    plant = cfg["plant"]
    act = cfg["actuator"]
    links = plant["links"]
    dt = cfg["env"]["dt"]
    half_rail = 0.5 * act["rail_length"]
    reach = sum(l["length"] for l in links)

    # The carriage is a prescribed-motion boundary condition in core::Plant, not a
    # free body. Here it is a slide joint carrying the chain; replay sets its qpos
    # directly, and a live sim would drive it with the position actuator below.
    cart_mass = plant["carriage_mass"]
    cart_ixx = cart_mass * (0.06 ** 2 + 0.05 ** 2) / 12.0

    chain = link_bodies(links)

    return f"""<!-- GENERATED by tools/make_mjcf.py from config.json. Do not edit. -->
<mujoco model="pidrl_cart_pendulum">
  <compiler angle="radian" autolimits="true"/>

  <!-- timestep and gravity from config.json; RK4 to match Plant::step, so a
       comparison against core is not confounded by the integrator. -->
  <option timestep="{dt:.9g}" integrator="RK4"
          gravity="0 0 -{plant['gravity']:.9g}"/>

  <visual>
    <headlight ambient="0.45 0.45 0.45" diffuse="0.55 0.55 0.55"/>
    <rgba haze="0.15 0.16 0.18 1"/>
    <global azimuth="90" elevation="-12" offwidth="1280" offheight="720"/>
  </visual>

  <asset>
    <texture name="grid" type="2d" builtin="checker" width="512" height="512"
             rgb1="0.20 0.21 0.23" rgb2="0.16 0.17 0.19"/>
    <material name="grid" texture="grid" texrepeat="8 8" reflectance="0.05"/>
    <material name="steel" rgba="0.42 0.44 0.47 1"/>
    <material name="carriage" rgba="0.78 0.79 0.80 1"/>
  </asset>

  <worldbody>
    <light pos="0 -1.2 2.2" dir="0 0.4 -1" diffuse="0.7 0.7 0.7"/>
    <geom name="floor" type="plane" size="3 2 0.05" pos="0 0 -0.35"
          material="grid" contype="0" conaffinity="0"/>

    <!-- Rail: {act['rail_length']:.9g} m of usable travel. Running off it is a
         termination decided in code, so this geom is visual only. -->
    <geom name="rail" type="capsule" fromto="-{half_rail:.9g} 0 0 {half_rail:.9g} 0 0"
          size="0.012" material="steel" contype="0" conaffinity="0"/>
    <geom name="stop_left" type="box" pos="-{half_rail:.9g} 0 0" size="0.008 0.03 0.03"
          material="steel" contype="0" conaffinity="0"/>
    <geom name="stop_right" type="box" pos="{half_rail:.9g} 0 0" size="0.008 0.03 0.03"
          material="steel" contype="0" conaffinity="0"/>

    <body name="cart" pos="0 0 0">
      <joint name="slide" type="slide" axis="1 0 0"
             range="-{half_rail:.9g} {half_rail:.9g}"/>
      <inertial pos="0 0 0" mass="{cart_mass:.9g}"
                diaginertia="{cart_ixx:.9g} {cart_ixx:.9g} {cart_ixx:.9g}"/>
      <geom name="carriage" type="box" size="0.05 0.035 0.025" material="carriage"
            contype="0" conaffinity="0"/>
{chain}    </body>
  </worldbody>

  <actuator>
    <!-- Only used by a live sim; replay writes qpos directly and ignores this.
         A belt drive is a position source, so the carriage is driven by position,
         not by force. kp is a stand-in for belt stiffness: raise it until the
         tracking error against the commanded trajectory stops mattering. -->
    <position name="cart_drive" joint="slide" kp="8000" kv="80"
              ctrlrange="-{half_rail:.9g} {half_rail:.9g}"/>
  </actuator>

  <sensor>
    <jointpos name="cart_x" joint="slide"/>
    <jointvel name="cart_v" joint="slide"/>
  </sensor>

  <keyframe>
    <!-- Hanging at rest: the state every episode starts from. -->
    <key name="hanging" qpos="0{' 3.14159265358979' * len(links)}"/>
    <key name="upright" qpos="0{' 0' * len(links)}"/>
  </keyframe>
</mujoco>
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("config", nargs="?", default=os.path.join(ROOT, "config.json"))
    ap.add_argument("-o", "--out", default=os.path.join(HERE, "pendulum.xml"))
    args = ap.parse_args()

    cfg = load_config(args.config)
    xml = build(cfg)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(xml)

    n = len(cfg["plant"]["links"])
    print(f"wrote {args.out}  ({n} link{'s' if n != 1 else ''}, "
          f"rail {cfg['actuator']['rail_length']:g} m, dt {cfg['env']['dt']:g})")


if __name__ == "__main__":
    sys.exit(main())
